name: All Contributors

on:
  schedule:
    # Run once a week on Sunday at midnight UTC
    - cron: '0 0 * * 0'
  workflow_dispatch: # Allow manual triggering

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  update-contributors:
    if: github.repository == 'imbhargav5/rooks'

    timeout-minutes: 20

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ci-setup
      # - uses: ./.github/actions/ci-checks
      - name: Enable Corepack
        run: corepack enable
      - name: Prepare package managers
        run: |
          corepack prepare pnpm@10.6.4 --activate
      - name: Generate list of contributors
        run: |
          pnpm contributors:update
          pnpm contributors:generate
      - name: Auto update Readme
        run: |
          pnpm update-package-list-to-markdown
      - name: Create or Update Pull request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: actions/all-contributors-update
          commit-message: Update Contributors List in Readme
          title: Update Contributors List in Readme
          body: Automatically generating contributors
          delete-branch: true
          labels: all-contributors-update
          draft: false
