name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          version: 12.x
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-  
      - name: Install project dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true' # Over here!
        run: yarn
      - name: yarn build
        run: yarn build:action
      - name: test
        run: yarn test
      - name: Generate docusaurus        
        run: yarn run readme-to-docs
      - name: Build docusaurus        
        run:  cd packages/docusaurus && yarn build
      - name: Commit docusaurus
        continue-on-error: true        
        run: |
          git add packages/docusaurus
          git -c user.name="imbhargav5" -c user.email="imbhargav5@users.noreply.github.com" \
            commit -m "Update ${{ steps.tags.outputs.new }} docusaurus [skip ci]" --no-verify --quiet
          git push "https://imbhargav5:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" master
      - name: Deploy docusaurus
        continue-on-error: true        
        env:
          ZEIT_TOKEN: ${{secrets.ZEIT_TOKEN}}
        run: cd packages/docusaurus && yarn run deploy --token $ZEIT_TOKEN
      - name: deploy
        env:
          ZEIT_TOKEN: ${{secrets.ZEIT_TOKEN}}
        run: yarn run deploy:dev --token $ZEIT_TOKEN
